version: '3.8'

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/idryab/TEST1
  # mariadb:
  #   name: mariadb
  #   driver: local
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: /Users/idryab/Desktop/incepE1R1P1LAST/srcs/requirements/mariadb

networks:
  inception:
    driver: bridge			

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - .env
    networks:
      - inception
    restart: always
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    depends_on:
      - mariadb
    volumes:
      - wordpress:/var/www/wordpress
    env_file:
      - .env
    networks:
      - inception
    restart: always
    expose:
      - "9000"
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/.
    # volumes:
    #   - mariadb:/var/lib/musql
    env_file:
      - .env
    networks:
      - inception
    restart: always
    expose:
      - "3306"

  